<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>9.3.5</Version>
    <AssemblyVersion>9.3.5.0</AssemblyVersion>
    <FileVersion>9.3.5.0</FileVersion>
    <Company>StreakWatch</Company>
    <Product>StreakWatch</Product>
    <Description>Twitch live detection and Firefox playback reliability utility</Description>

    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>StreakWatch</AssemblyName>
    <RootNamespace>StreakWatchV935</RootNamespace>
      <ApplicationIcon>Assets\StreakWatch.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
